`CI`: add workaround for `Carthage` timing out
`xcodebuild -list` loads all SPM dependencies, which includes our own repo (necessary to test `RevenueCat_CustomEntitlementComputation`):
```
Resolve Package Graph

Resolve Package Graph

Resolved source packages:
  CwlPreconditionTesting: https://github.com/mattgallagher/CwlPreconditionTesting.git @ 2.1.2
  swift-snapshot-testing: https://github.com/pointfreeco/swift-snapshot-testing @ 1.11.1
  CwlCatchException: https://github.com/mattgallagher/CwlCatchException.git @ 2.1.2
  Nimble: https://github.com/quick/nimble @ 10.0.0
  OHHTTPStubs: https://github.com/AliSoftware/OHHTTPStubs.git @ 9.1.0
  RevenueCat: https://github.com/RevenueCat/purchases-ios @ main
```

`Carthage` has as [hardcoded timeout of 60 seconds](https://github.com/Carthage/Carthage/blob/0.39.0/Source/CarthageKit/XCDBLDExtensions.swift#L79). This has been failing ti due to our repo size growing combined with CircleCI's network issues.
To prevent that, this updates all lanes that use `Carthage` to pre-load SPM dependencies by calling `xcodebuild -list` first.