`DeviceCache`: added verbose logs for `init`/`deinit`
Equivalent to #2082.
This change will help continue debugging [CSDK-517].

While debugging locally I ran into this crash:
```
Test Case '-[StoreKitUnitTests.UserDefaultsDefaultTests testDefaultIsRevenueCatSuiteIfStandardDoesNotContainUserID]' started.
RevenueCat/DeviceCache.swift:85: Fatal error: [Purchases] - Cached appUserID has been deleted from user defaults.
This leaves the SDK in an undetermined state. Please make sure that RevenueCat
entries in user defaults don't get deleted by anything other than the SDK.
More info: https://rev.cat/userdefaults-crash
```

But that should have been impossible because the current test had not initialized `Purchases` or `DeviceCache`, which showed that there was a leaking `DeviceCache` from another test.