Revert "`SPM`: added `APPLICATION_EXTENSION_API_ONLY` flag to `RevenueCat` and `ReceiptParser` (#2217)" (#2225)
This reverts commit 02c2bcec4b51cc59c07cb09c4a62e160c919f7bd.

Unfortunately this breaks SPM integration under some conditions (see
#2223):
> error: The package product 'RevenueCat' cannot be used as a dependency
of this target because it uses unsafe build flags. (in target
'PurchaseTester' from project 'PurchaseTester')

I haven't been able to reproduce this locally, but better to remove this
for now until `SPM` adds a way to set this flag without using unsafe
flags.